# Generated by Django 3.1.1 on 2022-03-09 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=uuid.uuid1, max_length=50, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('image', models.CharField(max_length=20)),
            ],
        ),
    ]
