# Generated by Django 4.0.3 on 2022-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image_flag',
            field=models.IntegerField(),
        ),
    ]
