# Generated by Django 4.0.3 on 2022-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
